// GENERATED by `bun run conformance` - do not hand-edit. Pinned SHA-256
// digests of every built-in animal's bundled sheets and the shared
// LICENSE-ART.md, read straight from packages/tabpet/assets/ so a
// contributor adding an animal never copies a digest by hand; `bun run
// conformance --check` fails if this file drifts from animals.json's own copy.
let pinnedLicenseSHA256 = "4fb1ed5b30d635817187840dbae37d75ae537199fea1fbc2227c76303346a334"

struct PinnedSheetHashes {
    let idle: String
    let run: String
    let sit: String
}

let pinnedSheetSHA256: [String: PinnedSheetHashes] = [
    "panda": PinnedSheetHashes(
        idle: "2d7af0fc6b9191e9125c84b1c11cbd9c77179795981f257479ab8c714cfeb7e8",
        run: "caa7b912d17950941a9bf3d4c7eefac45063f8093987b903a3b4ad9fc92b6196",
        sit: "afcad7f932390b2c50a9d307843ad570468dafa1bee7deec9dfd1df9dd4f97e3"
    ),
    "cat": PinnedSheetHashes(
        idle: "b96835ad35e64d37807f3b61d3198691171072bf8655c0bdf4a5e27c5f1cd160",
        run: "07f8f141414d3afe39f916208b5c73cb0e7f6483863a0627b931adc31be0f4a6",
        sit: "fe66ab9edeb8df5e85934bc6b97c6ab1de9745750b35c4bde694216b095a6568"
    ),
    "turtle": PinnedSheetHashes(
        idle: "3a022f49685b7c74258b28d6839ea25cef4efef7f24018dcd6e73bc3c549e320",
        run: "2d7a1bdfad65e9bd5328da5de13c45043a576639374dffbbcb9c366c2eea9b28",
        sit: "d18dba6692aac34cf9dc4a64ed10a555889422cc567ea0cc48435a4611d0bad1"
    ),
    "raccoon": PinnedSheetHashes(
        idle: "626a5469174c99bb8f2c83d1b9213b25b459a5d226305881042617d8cfc2bc62",
        run: "6198110dfde5e76bf80c614afe75fca1ba1914a1ca77b14f84a44322f522fdea",
        sit: "e267f80ea2a8f663195a86d81f56cb43c99fe67083dc6611762d39dca2b86abe"
    ),
    "bird": PinnedSheetHashes(
        idle: "90d976aba08b682c972214660a0ea061f1e69593e798bd49599383be802cdb1f",
        run: "278c20084261e90c9a7c94e891148e52c533b4821e103b1948eceab5af040c08",
        sit: "c075582cb56202e987f5925caa7d33e9b52bc060b8d9eda9e23fba4b08e92c05"
    ),
    "squirrel": PinnedSheetHashes(
        idle: "2c9bf816e9e643f490223b73e24337b6629508e744c885f1b40cf852a6ac39c1",
        run: "a2ca217ded2bef7208dd2ba4483ace83017dde52a83442d62e76266d3c789fd2",
        sit: "ece0effa74078bdc89070aba8c03b2c81ace56fb6d28130b87d8e76a2ea3a1c4"
    ),
]
